### ISSUE TITLE
Some Random Tiles Not Appearing

### ISSUE THREAD

**Issue by kaiiboraka** [heygleeson/godot-ldtk-importer#20]
Hello, 

In this screenshot, I have an autolayer to add hanging elements below tiles. The way it's currently set up, it selects multiple "individual tiles," which it then chooses from randomly to paint along the edge. You can see how it SHOULD look on the right side on LDTK, but if you see in the top left in Godot, only some of the tiles are appearing. At first I thought it was only grabbing 1 of the tiles, but actually all 3 are still present, it's just that some are missing for some currently unknown reason.

![image](https://github.com/heygleeson/godot-ldtk-importer/assets/7596816/df187c45-ef50-428a-b6ee-8bd21f6d9196)

I am currently using Godot 4.3.beta2.mono and LDtk 1.5.3-64bit.

**Comment by heygleeson** [comment]
Thanks for the report! A recent update had broken overlapping tiles, which is what was happening here. Godot's new TileMapLayers only support one tile per cell, but it's possible to create child TileMapLayers to account for additional tiles.

Fixed in [v2.0.1](https://github.com/heygleeson/godot-ldtk-importer/releases/tag/2.0.1)
